# Generated by Django 3.0.6 on 2020-05-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Userngo',
        ),
    ]
