# Generated by Django 3.0.6 on 2020-05-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200527_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=122)),
                ('medicine_name', models.CharField(max_length=122)),
                ('pickup_address', models.CharField(max_length=12)),
                ('purpose', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
