# Generated by Django 3.0.6 on 2020-05-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donor_name',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='donations',
            name='medicine_name',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='donations',
            name='pickup_address',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='donations',
            name='purpose',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdonor',
            name='email',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='userdonor',
            name='name',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='userdonor',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userdonor',
            name='phone',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='address',
            field=models.TextField(max_length=102),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='certification',
            field=models.TextField(max_length=102),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='email',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='name',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userngo',
            name='phone',
            field=models.TextField(max_length=12),
        ),
    ]
