# Generated by Django 3.0.6 on 2020-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200601_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userngo',
            name='date',
            field=models.DateField(),
        ),
    ]
