# Generated by Django 3.0.6 on 2020-05-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200601_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='accepted_by',
            field=models.TextField(default='None', max_length=12),
        ),
    ]
