# Generated by Django 3.0.6 on 2020-05-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200601_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='pickup_address',
            field=models.TextField(max_length=120),
        ),
    ]
