# Generated by Django 3.1 on 2020-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200601_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='email',
            field=models.TextField(default='xyz', max_length=122),
        ),
    ]
